import express from "express";
import { dbConnection } from "./db/connection.js";
import userRoutes from "./modules/user/user.routes.js";
import taskRoutes from "./modules/task/task.routes.js";
const app = express();
const port = 3000;
dbConnection();
app.use(express.json());
app.use(userRoutes);
app.use(taskRoutes);
app.get("/", (req, res) => res.send("Hello World!"));
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
